# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dac34311da046d82961798322b98fbe2554822901b49e2f212078be459f2e9ab8860513bffdcaac96c89cccd8e90cd23df9c9f906fd125dd2517b5bd7e5ea90d

test:
  secret_key_base: 195a90264f11b42a516f4178c29afc04da339d3dd56fe6dee2d7c7caf76b4ef3608d9f465c855d3f42e666af347080d0a55ef21b8d3a46fa123591c3a669efb3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
